os: linux
dist: focal
language: cpp

env:
  global:
    CMAKE_GENERATOR=Ninja

jobs:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'        
        packages:
          - libboost-dev
          - libboost-test-dev
          - libsdl2-dev
          - cmake 
          - ninja-build
    env:
      MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      TARGET=x86_64-linux-gnu

before_install:
  eval "${MATRIX_EVAL}"

script:
  - chmod +x ./scripts/*
  - ./scripts/pre-build.sh
  - ./scripts/build.sh
